### ISSUE TITLE
The amsCd component is wrongly capitalized

### ISSUE THREAD

**Issue by dpvc** [mathjax/MathJax-src#335]
The `amsCd` component has the wrong capitalization, so doesn't load properly with `\require{amsCd}` or via autoloading.

**Comment by nasosev** [comment]
@dpvc is this really fixed in 3.0.1? The file still is capitalised "amscd.js" at https://cdn.jsdelivr.net/npm/mathjax@3.0.1/es5/input/tex/extensions/amscd.js .

**Comment by dpvc** [comment]
Argh!  It is fixed in the source repository (the `es5` directory that gets built and saved as the npm package has the properly renamed file); but when the `es5` directory gets copied to the main MathJax repository, the old version needed to be removed from the repository and the new one added.  I did add the new `assistive-mml` extension, for example, but missed this one because on MacOS, which is not case sensitive, both are the "same" name, and so they didn't show up as differences in `git status`.  Argh!

We will need to do a v3.0.2 release to fix that.  There is another issue as well, so we may make another release soon to fix those two items.

**Comment by dpvc** [comment]
I've opened mathjax/MathJax#2326 to make sure this gets done in the main MathJax repository.

**Comment by dpvc** [comment]
@nasosev, In the meantime, you can use

``` javascript
MathJax = {
  loader: {
    source: {
      '[tex]/amsCd': '[tex]/amscd'
    }
  }
};
```

to remap the correct capitalization to the incorrect one.  This will allow you to use `\require{amsCd}` or `load: ['[tex]/amsCd']` with the current CDN setup.

**Comment by nasosev** [comment]
> @nasosev, Argh! It is fixed in the source repository (the `es5` directory that gets built and saved as the npm package has the properly renamed file); but when the `es5` directory gets copied to the main MathJax repository, the old version needed to be removed from the repository and the new one added. I did add the new `assistive-mml` extension, for example, but missed this one because on MacOS, which is not case sensitive, both are the "same" name, and so they didn't show up as differences in `git status`. Argh!
> 
> We will need to do a v3.0.2 release to fix that. There is another issue as well, so we may make another release soon to fix those two items.
@dpvc 
FYI, the problem persists in v3.0.5: https://cdn.jsdelivr.net/npm/mathjax@3/es5/input/tex/extensions/amsCd.js does not exist but amscd.js is there.

**Comment by dpvc** [comment]
@nasosev, oh  no, not again!  I thought I had taken care of that!  Apparently I still didn't get it right.

We will be making a 3.1.0 release later this month or early next month, and I will see if I can't get it taken care of during that.  I will rename the file right now to make sure that it is correct when the next version is released.
